import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import type { AnalyzeOptions, AnalyzedFile, ComponentUsage, ProposedRemote, RouteMatch, SplitPlan } from "./types.js";
const EXT = new Set([".ts", ".tsx", ".js", ".jsx"]);
const FEATURES = "features";
const ROUTES = /routes?\.(tsx?|jsx?)$/i;
export function collectSourceFiles(rootDir: string): string[] { const out: string[] = []; const walk = (d: string) => { for (const e of readdirSync(d)) { const p = join(d, e); if (statSync(p).isDirectory()) { if (e !== "node_modules" && e !== "dist") walk(p); } else if (EXT.has(extname(e))) out.push(p); } }; walk(rootDir); return out.sort(); }
export function parseImports(s: string): string[] { const set = new Set<string>(); for (const re of [/import\s+(?:type\s+)?(?:[\w*{}\s,]+)\s+from\s+['"]([^'"]+)['"]/g, /import\s+['"]([^'"]+)['"]/g]) for (const m of s.matchAll(re)) set.add(m[1]); return [...set]; }
export function resolveRelativeImport(from: string, imp: string, root: string, known: Set<string>): string | undefined { if (!imp.startsWith(".")) return undefined; const base = resolve(dirname(from), imp); for (const c of [base, base + ".ts", base + ".tsx", join(base, "index.ts")]) if (known.has(c)) return relative(root, c); }
function feature(path: string): string | undefined { const p = path.split(/[/\\]/); const i = p.indexOf(FEATURES); return i >= 0 && i < p.length - 1 ? p[i + 1] : undefined; }
export function analyzeFiles(rootDir: string, abs: string[], featuresDir: string): AnalyzedFile[] { const known = new Set(abs); return abs.map((absolutePath) => { const relativePath = relative(rootDir, absolutePath); const imports = parseImports(readFileSync(absolutePath, "utf8")).map((i) => resolveRelativeImport(absolutePath, i, rootDir, known)).filter((x): x is string => !!x); return { relativePath, absolutePath, imports, folderFeature: feature(relativePath) }; }); }
export function extractRoutes(files: AnalyzedFile[]): RouteMatch[] { const routes: RouteMatch[] = []; for (const f of files) { if (!ROUTES.test(f.relativePath)) continue; for (const m of readFileSync(f.absolutePath, "utf8").matchAll(/path:\s*['"]([^'"]+)['"]/g)) routes.push({ path: m[1], sourceFile: f.relativePath, featureHint: m[1].split("/").filter(Boolean)[0] }); } return routes; }
export function buildComponentUsage(files: AnalyzedFile[]): ComponentUsage[] { const m = new Map<string, Set<string>>(); for (const f of files) for (const i of f.imports) { const s = m.get(i) ?? new Set(); s.add(f.relativePath); m.set(i, s); } return [...m.entries()].map(([file, s]) => ({ file, importCount: s.size, importedBy: [...s].sort() })).sort((a,b)=>b.importCount-a.importCount); }
function routesFor(name: string, routes: RouteMatch[]) { return routes.filter(r => r.featureHint === name || r.path.startsWith("/" + name)).map(r => r.path).sort(); }
function isSharedPath(file: string) { return file.includes("/shared/") || file.startsWith("shared/"); }
function sharedList(usage: ComponentUsage[], remotes: ProposedRemote[], files: AnalyzedFile[]) { const out: string[] = []; for (const u of usage) { let rc = 0; for (const r of remotes) { const imps = files.filter(f => r.files.includes(f.relativePath)).flatMap(f => f.imports); if (imps.includes(u.file)) rc++; } if (rc >= 2 || (isSharedPath(u.file) && u.importCount >= 2)) out.push(u.file); } return [...new Set(out)].sort(); }
export function analyzeMonolith(options: AnalyzeOptions): SplitPlan { const rootDir = resolve(options.rootDir); const files = analyzeFiles(rootDir, collectSourceFiles(rootDir), options.featuresDir ?? FEATURES); const routes = extractRoutes(files); const usage = buildComponentUsage(files); const groups = new Map<string, AnalyzedFile[]>(); for (const f of files) { if (!f.folderFeature) continue; const g = groups.get(f.folderFeature) ?? []; g.push(f); groups.set(f.folderFeature, g); } const remotes: ProposedRemote[] = [...groups.entries()].map(([name, group]) => { const filePaths = group.map(f => f.relativePath).sort(); const rs = routesFor(name, routes); const strategies: ProposedRemote["strategies"] = ["folder-based"]; if (rs.length) strategies.push("route-based"); if (group.some(f => f.imports.length)) strategies.push("import-graph"); return { name, strategies, routes: rs, files: filePaths, entryCandidates: filePaths.filter(p => /Page\.tsx?$/.test(p)), sharedDependencies: [], confidence: Math.min(0.65 + (rs.length ? 0.15 : 0) + (group.length > 1 ? 0.1 : 0), 0.95), rationale: [`Folder: ${group.length} files`, rs.length ? `Routes: ${rs.join(", ")}` : "No routes"] }; }).sort((a,b) => a.name.localeCompare(b.name)); const shared = sharedList(usage, remotes, files); for (const r of remotes) r.sharedDependencies = shared.filter(s => files.filter(f => r.files.includes(f.relativePath)).some(f => f.imports.includes(s))); const assigned = new Set(remotes.flatMap(r => r.files)); const shellFiles = files.map(f => f.relativePath).filter(p => !assigned.has(p) && !shared.includes(p)).sort(); return { analyzedAt: new Date().toISOString(), rootDir, summary: { totalFiles: files.length, proposedRemotes: remotes.length, sharedFiles: shared.length, shellFiles: shellFiles.length }, heuristics: { "route-based": { enabled: routes.length > 0, notes: "URL prefixes" }, "folder-based": { enabled: groups.size > 0, notes: "features/<name>" }, "import-graph": { enabled: true, notes: "import edges" }, "component-frequency": { enabled: true, notes: "reuse count" } }, remotes, shell: { files: shellFiles, rationale: ["Bootstrap and routing shell"] }, shared: { files: shared, rationale: ["Multi-remote imports"] }, importGraph: { nodes: files.map(f => f.relativePath), edges: files.flatMap(f => f.imports.map(to => ({ from: f.relativePath, to }))) }, warnings: ["Dynamic imports not resolved in prototype."] }; }
