blank_issues_enabled: false
contact_links:
  - name: Questions / Ideas
    url: https://github.com/federation-wizards/fwiz/discussions
    about: Please use Discussions for Q&A and open-ended ideas.


