import { spawn, type ChildProcess } from 'node:child_process';
import type { Server } from 'node:http';
import { loadFwizConfig } from '../config/load.js';
import { DevError } from './errors.js';
import { buildDevPlan } from './plan.js';
import { findPortConflicts } from './ports.js';
import { createDevProxyServer } from './proxy.js';
import { buildServerRows, formatServerTable } from './table.js';
import type { DevPlan, DevProcessSpec, RunDevOptions } from './types.js';
interface RunningDevSession { children: ChildProcess[]; proxyServer?: Server; shutdownPromise?: Promise<void>; }
let activeSession: RunningDevSession | undefined;
const startProcess = (spec: DevProcessSpec, cwd: string): ChildProcess => spawn(spec.command, { cwd, shell: true, stdio: 'inherit', env: { ...process.env, PORT: String(spec.port), FWIZ_DEV_PORT: String(spec.port) } });
async function assertPortsAvailable(plan: DevPlan) { const conflicts = await findPortConflicts([...plan.processes.map((p) => p.port), plan.proxyPort]); if (conflicts.length) throw new DevError(`Port conflict detected on: ${conflicts.join(', ')}. Stop the blocking process or update fwiz.config.yaml.`); }
async function shutdownSession(session: RunningDevSession) { if (session.shutdownPromise) return session.shutdownPromise; session.shutdownPromise = (async () => { for (const child of session.children) if (!child.killed && child.pid) child.kill('SIGTERM'); await Promise.all(session.children.map((child) => new Promise<void>((resolve) => { if (child.exitCode !== null || child.killed) return resolve(); child.once('exit', () => resolve()); setTimeout(() => { if (!child.killed && child.pid) child.kill('SIGKILL'); resolve(); }, 5000).unref(); }))); if (session.proxyServer) await new Promise<void>((resolve, reject) => session.proxyServer?.close((e) => (e ? reject(e) : resolve()))); })(); return session.shutdownPromise; }
export async function runDev(options: RunDevOptions): Promise<void> { if (activeSession) throw new DevError('A dev session is already running in this process.'); const plan = buildDevPlan(loadFwizConfig(options.cwd), options.host); await assertPortsAvailable(plan); const session: RunningDevSession = { children: plan.processes.map((process) => startProcess(process, options.cwd)) }; activeSession = session; session.proxyServer = await createDevProxyServer(plan.proxyRoutes, plan.proxyPort); console.log(formatServerTable(buildServerRows(plan.processes, plan.proxyUrl))); console.log(`Starting host "${plan.hostName}" with ${plan.processes.length - 1} remote(s).`); console.log(`Remote proxy available at ${plan.proxyUrl}`); await new Promise<void>((resolve) => { const finish = () => void shutdownSession(session).finally(() => { activeSession = undefined; resolve(); }); process.once('SIGINT', () => { console.log('\nReceived SIGINT. Shutting down dev servers...'); finish(); }); process.once('SIGTERM', () => { console.log('\nReceived SIGTERM. Shutting down dev servers...'); finish(); }); for (const child of session.children) child.once('exit', (code, signal) => { if (code !== 0 && signal !== 'SIGTERM') console.error(`Dev process exited unexpectedly (code=${code ?? 'null'}, signal=${signal ?? 'null'}).`); finish(); }); }); }
