import type { FwizConfig, WorkspaceType } from '../config/types.js';
import { DevError } from './errors.js';
import { allocateProxyPort } from './ports.js';
import type { DevPlan, DevProcessSpec, DevProjectEntry } from './types.js';
const formatUrl = (port: number) => `http://localhost:${port}`;
export function resolveDevCommand(entry: DevProjectEntry, workspaceType: WorkspaceType, port: number): string { if (entry.dev?.command) return entry.dev.command.replaceAll('{port}', String(port)); if (entry.project) { if (workspaceType === 'nx') return `npx nx run ${entry.project}:serve --port=${port}`; if (workspaceType === 'turbo') return `npx turbo run dev --filter=${entry.project} -- --port=${port}`; } throw new DevError(`No dev command configured for "${entry.name}". Set dev.command or project in fwiz.config.yaml.`); }
const createProcessSpec = (entry: DevProjectEntry, role: DevProcessSpec['role'], workspaceType: WorkspaceType): DevProcessSpec => ({ name: entry.name, role, port: entry.port, command: resolveDevCommand(entry, workspaceType, entry.port), url: formatUrl(entry.port) });
export function resolveHost(config: FwizConfig, hostName?: string) { const name = hostName ?? config.hosts[0]?.name; if (!name) throw new DevError('No hosts configured in fwiz.config.yaml.'); const host = config.hosts.find((entry) => entry.name === name); if (!host) throw new DevError(`Host "${name}" was not found. Available hosts: ${config.hosts.map((h) => h.name).join(', ')}.`); return host; }
export function buildDevPlan(config: FwizConfig, hostName?: string): DevPlan { const host = resolveHost(config, hostName); const processes = [createProcessSpec(host, 'host', config.workspace.type), ...config.remotes.map((remote) => createProcessSpec(remote, 'remote', config.workspace.type))]; const proxyPort = allocateProxyPort(host.port, processes.map((p) => p.port)); return { hostName: host.name, processes, proxyPort, proxyUrl: formatUrl(proxyPort), proxyRoutes: config.remotes.map((remote) => ({ name: remote.name, path: `/${remote.name}`, target: formatUrl(remote.port) })) }; }
